### ISSUE TITLE
Easier solution: Use ZSH

### ISSUE THREAD

**Issue by jplatte** [dxa4481/Pastejacking#6]
I think it should be mentioned that this doesn't work with zsh, as it only executes commands when the user presses enter, not when pasting a newline.

**Comment by sugar700** [comment]
Uh, that's not true at all. The exploit could be changed to make it work in zsh (although whether it will work depends on terminal), see https://xfix.github.io/mystery-zone/command.html for an example. This is proof of concept either way.

**Comment by inputjoker** [comment]
it works well with zsh using terminator in debian.

**Comment by jplatte** [comment]
Okay, that's definitely interesting, but seems to do something else than just paste newlines. It also works without the JS paste API stuff, which I'd say makes it a lot more powerfull, however it actually works.

**Comment by lotheac** [comment]
This particular feature in zsh (>=5.1) is the "bracketed paste mode" support. The linked page's payload includes the terminating sequence for bracketed paste mode in order to work around that, but on xterm it fails for me.

http://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Bracketed-Paste-Mode

**Comment by dxa4481** [comment]
See here https://github.com/robbyrussell/oh-my-zsh/issues/1742
